name: drift_encryption_sample
description: A small Flutter app demonstrating how to use drift with encryption.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  drift: ^2.0.2+1
  sqlcipher_flutter_libs: ^0.6.0
  flutter:
    sdk: flutter
  path_provider: ^2.0.11
  path: ^1.8.1
  sqlite3: '>=1.8.0 <3.0.0'

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  drift_dev: ^2.0.2
  build_runner: ^2.2.0

flutter:
  uses-material-design: true
