name: sqlparser
description: Parses sqlite statements and performs static analysis on them
version: 0.2.0
homepage: https://github.com/simolus3/moor/tree/develop/sqlparser
#homepage: https://moor.simonbinder.eu/
issue_tracker: https://github.com/simolus3/moor/issues
author: Simon Binder <oss@simonbinder.eu>

environment:
  sdk: '>=2.2.2 <3.0.0'

dependencies:
  meta: ^1.1.0
  collection: ^1.14.11
  source_span: ^1.5.5

dev_dependencies:
  test: ^1.6.0
  test_core: any # version will be determined by "test"
  path: ^1.6.0
  coverage:
    git: https://github.com/simolus3/coverage.git