name: sqlparser
description: Parses sqlite statements and performs static analysis on them
version: 0.32.0-dev
homepage: https://github.com/simolus3/drift/tree/develop/sqlparser
repository: https://github.com/simolus3/drift
#homepage: https://drift.simonbinder.eu/
issue_tracker: https://github.com/simolus3/drift/issues

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  meta: ^1.3.0
  collection: ^1.15.0
  source_span: ^1.8.0
  charcode: ^1.2.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.17.4
  path: ^1.8.0
  ffi: ^2.0.0
  sqlite3: ^2.0.0
