name: sqlparser
description: Parses sqlite statements and performs static analysis on them
version: 0.20.1
homepage: https://github.com/simolus3/moor/tree/develop/sqlparser
#homepage: https://moor.simonbinder.eu/
issue_tracker: https://github.com/simolus3/moor/issues

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  meta: ^1.3.0
  collection: ^1.15.0
  source_span: ^1.8.0
  charcode: ^1.2.0

dev_dependencies:
  test: ^1.17.4
  path: ^1.8.0
  ffi: ^1.0.0
  sqlite3: ^1.0.0
