name: analyzer_load_moor_plugin
version: 1.0.0
description: This pubspec is a part of moor and determines the version of the moor analyzer to load

environment: 
  sdk: '>=2.9.0 <3.0.0'

dependencies:
 moor_generator: ^3.0.0
 web_socket_channel: ^1.0.15

# These overrides are only needed when working on the plugin with useDebuggingVariant = false (not recommended)

#dependency_overrides:
# moor_generator:
#  path: /path/to/moor/moor_generator
# sqlparser:
#  path: /path/to/moor/sqlparser