name: with_built_value
publish_to: none
version: 1.0.0

environment:
  sdk: '>=2.14.0 <4.0.0'

dependencies:
  drift: ^2.11.0
  built_value: ^8.0.0

dev_dependencies:
  drift_dev: ^2.11.0
  built_value_generator: ^8.1.3
  build_runner: ^2.0.0
