name: moor
description: Moor is a safe and reactive persistence library for Dart applications
version: 4.3.1
repository: https://github.com/simolus3/moor
homepage: https://moor.simonbinder.eu/
issue_tracker: https://github.com/simolus3/moor/issues

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  async: ^2.5.0
  convert: ^3.0.0
  collection: ^1.15.0
  meta: ^1.3.0
  pedantic: ^1.10.0
  stream_channel: ^2.1.0
  sqlite3: ^1.0.0

dev_dependencies:
  build_test: ^2.0.0
  build_runner_core: ^7.0.0
  moor_generator: any
  uuid: ^3.0.0
  path: ^1.8.0
  build_runner: ^2.0.0
  test: ^1.17.0
  mockito: ^5.0.7
  rxdart: ^0.27.0

dependency_overrides:
  moor_generator:
    path: ../moor_generator
  sqlparser:
    path: ../sqlparser
