name: moor
description: Moor is a safe and reactive persistence library for Dart applications
version: 1.7.0
repository: https://github.com/simolus3/moor
homepage: https://moor.simonbinder.eu/
issue_tracker: https://github.com/simolus3/moor/issues
authors:
  - Simon Binder <oss@simonbinder.eu>
maintainer: Simon Binder (@simolus3)

environment:
  sdk: '>=2.2.2 <3.0.0'

dependencies:
  meta: ^1.0.0
  collection: ^1.0.0
  synchronized: ^2.1.0
  pedantic: any

dev_dependencies:
  moor_generator: ^1.6.0
  build_runner: '>=1.3.0 <2.0.0'
  build_test: ^0.10.8
  test: ^1.6.4
  test_api: '>=0.2.0 <1.0.0'
  test_core: '>=0.2.0 <1.0.0'
  mockito: ^4.1.0
  grinder: ^0.8.3
  coverage: ^0.12.4

dependency_overrides:
  moor_generator:
    path: ../moor_generator
  sqlparser:
    path: ../sqlparser
  # Temporarily use my fork because it can collect coverage when running tests with the test runner
  coverage:
    git: https://github.com/simolus3/coverage.git