name: migrations_example
publish_to: none
version: 1.0.0

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  moor:

dev_dependencies:
  moor_generator:
  build_runner: ^2.0.0
  test: ^1.15.4

dependency_overrides:
  drift:
    path: ../../drift
  drift_dev:
    path: ../../drift_dev
  moor:
    path: ../../moor
  moor_generator:
    path: ../../moor_generator
  sqlparser:
    path: ../../sqlparser
