name: web
description: Run integration tests for Moor on the web
environment:
  sdk: '>=2.6.0 <3.0.0'

dependencies:
  drift:
  drift_testcases:
    path: ../drift_testcases

dev_dependencies:
  test: ^1.5.0
  build_runner:
  build_web_compilers:
  drift_dev: ^1.0.0

dependency_overrides:
  drift:
    path: ../../../drift
  drift_dev:
    path: ../../../drift_dev
  sqlparser:
    path: ../../../sqlparser