name: with_built_value
publish_to: none
version: 1.0.0

environment:
  sdk: '>=2.6.0 <3.0.0'

dependencies:
  moor: ^4.0.0
  built_value: ^8.0.0

dev_dependencies:
  moor_generator: ^4.0.0
  built_value_generator: ^8.1.1
  build_runner: ^2.0.0
dependency_overrides:
  drift:
    path: ../../drift
  moor:
    path: ../../moor
  moor_generator:
    path: ../../moor_generator
  sqlparser:
    path: ../../sqlparser

  # todo: Remove after https://github.com/google/built_value.dart/pull/1085 gets released
  analyzer: ^2.0.0
