name: plugin_example
description: Playground to test the analyzer plugin

environment:
  sdk: '>=2.4.0 <3.0.0'

dependencies:
  moor:
    path: ../../moor

dev_dependencies:
  pedantic: ^1.7.0
  test: ^1.5.0
