name: drift_sqflite
description: A Flutter-only implementation of a drift database, based on the `sqflite` package.
version: 2.0.1
repository: https://github.com/simolus3/drift
homepage: https://drift.simonbinder.eu/
issue_tracker: https://github.com/simolus3/drift/issues

topics:
  - drift
  - database
  - sqflite

funding:
  - https://github.com/sponsors/simolus3

environment:
  sdk: '>=2.12.0 <4.0.0'

dependencies:
  drift: ^2.0.0
  sqflite: ^2.1.0
  path: ^1.8.0
  flutter:
    sdk: flutter

dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  drift_testcases:
    path: ../extras/integration_tests/drift_testcases

flutter:
  assets:
    - test_asset.db
