name: moor_generator
description: Dev-dependency to generate table and dataclasses together with the moor package.
version: 3.3.1
repository: https://github.com/simolus3/moor
homepage: https://moor.simonbinder.eu/
issue_tracker: https://github.com/simolus3/moor/issues

environment:
  sdk: '>=2.6.0 <3.0.0'

dependencies:
  collection: ^1.14.0
  recase: '>=2.0.1 <4.0.0'
  meta: ^1.1.0
  path: ^1.6.0
  json_annotation: ^3.0.0
  stream_transform: '>=0.0.20 <2.0.0'

  # CLI
  args: ^1.5.0
  logging: '>=0.11.0 <1.0.0'
  cli_util: ^0.1.0

  # Moor-specific analysis
  moor: ^3.0.0
  sqlparser: ^0.11.0-dev

  # Dart analysis
  analyzer: '^0.40.0'
  analyzer_plugin_fork:
    path: /home/simon/programming/analyzer_plugin_fork
  source_span: ^1.5.5

  # Build system
  build: ^1.1.0
  build_resolvers: ^1.3.3
  build_config: '>=0.3.1 <1.0.0'
  dart_style: ^1.3.3
  source_gen: ^0.9.4

dev_dependencies:
  test: ^1.6.0
  build_runner: ^1.6.7
  build_test: ^0.10.10
  json_serializable: ^3.0.0

executables:
  moor_generator:

dependency_overrides:
  sqlparser:
   path: ../sqlparser
  moor:
    path: ../moor
