name: moor
description: Moor has been renamed to Drift.
version: 4.6.1+2
repository: https://github.com/simolus3/drift
homepage: https://drift.simonbinder.eu/
issue_tracker: https://github.com/simolus3/drift/issues

environment:
  sdk: '>=2.13.0 <3.0.0'

dependencies:
  async: ^2.5.0
  convert: ^3.0.0
  collection: ^1.15.0
  drift: ^1.1.0
  meta: ^1.3.0
  stream_channel: ^2.1.0
  sqlite3: '>=1.0.0 <3.0.0'
