name: drift
description: Drift is a reactive library to store relational data in Dart and Flutter applications.
version: 2.12.1
repository: https://github.com/simolus3/drift
homepage: https://drift.simonbinder.eu/
issue_tracker: https://github.com/simolus3/drift/issues

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  async: ^2.5.0
  convert: ^3.0.0
  collection: ^1.15.0
  js: ^0.6.3
  meta: ^1.3.0
  stream_channel: ^2.1.0
  sqlite3: ^2.0.0
  path: ^1.8.0

dev_dependencies:
  archive: ^3.3.1
  build_test: ^2.0.0
  build_runner_core: ^7.0.0
  build_verify: ^3.0.0
  build_web_compilers: ^4.0.3
  drift_dev: any
  drift_testcases:
    path: ../extras/integration_tests/drift_testcases
  http: ^0.13.4
  lints: ^2.0.0
  uuid: ^4.0.0
  build_runner: ^2.0.0
  test: ^1.17.0
  mockito: ^5.0.7
  rxdart: ^0.27.0
  shelf: ^1.3.0
  stack_trace: ^1.10.0
  test_descriptor: ^2.0.1
