name: drift
description: Drift is a reactive library to store relational data in Dart and Flutter applications.
version: 2.20.1
repository: https://github.com/simolus3/drift
homepage: https://drift.simonbinder.eu/
issue_tracker: https://github.com/simolus3/drift/issues

topics:
  - drift
  - database

funding:
  - https://github.com/sponsors/simolus3

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  async: ^2.5.0
  convert: ^3.0.0
  collection: ^1.15.0
  meta: ^1.3.0
  stream_channel: ^2.1.0
  sqlite3: ^2.4.3
  path: ^1.8.0
  stack_trace: ^1.11.1
  web: ^1.0.0

dev_dependencies:
  archive: ^3.3.1
  analyzer: ^6.4.1
  build_test: ^2.0.0
  build_runner_core: ^7.0.0
  build_verify: ^3.1.0
  build_web_compilers: ^4.0.3
  drift_dev: any
  drift_testcases:
    path: ../extras/integration_tests/drift_testcases
  http: ^1.2.1
  lints: ^4.0.0
  uuid: ^4.4.0
  build_runner: ^2.0.0
  test: ^1.17.0
  mockito: ^5.4.3
  shelf: ^1.3.0
  test_descriptor: ^2.0.1
  vm_service: ^14.0.0
  rxdart: ^0.28.0
  build_daemon: ^4.0.2
