name: drift_dev
description: Dev-dependency for users of drift. Contains the generator and development tools.
version: 2.13.0-dev
repository: https://github.com/simolus3/drift
homepage: https://drift.simonbinder.eu/
issue_tracker: https://github.com/simolus3/drift/issues
topics:
  - codegen
  - build-runner
  - drift
  - database

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  charcode: ^1.2.0
  collection: ^1.14.0
  recase: '>=2.0.1 <5.0.0'
  meta: ^1.1.0
  path: ^1.6.0
  json_annotation: ^4.8.0
  stream_transform: '>=0.1.0 <3.0.0'

  # CLI
  args: ">=1.5.0 <3.0.0"
  logging: '>=0.11.0 <2.0.0'
  cli_util: '>=0.2.0 <0.5.0'
  yaml: ^3.1.0
  io: ^1.0.3

  # Drift-specific analysis and apis
  drift: '>=2.13.0 <2.14.0'
  sqlite3: '>=0.1.6 <3.0.0'
  sqlparser: '^0.32.0'

  # Dart analysis
  analyzer: '>=5.12.0 <7.0.0'
  analyzer_plugin: ^0.11.0
  source_span: ^1.5.5
  package_config: ^2.0.0
  pub_semver: ^2.0.0

  # Build system
  build: ^2.0.0
  build_resolvers: ^2.4.0
  build_config: '>=0.3.1 <2.0.0'
  dart_style: '>=1.3.3 <3.0.0'
  source_gen: '>=0.9.4 <2.0.0'
  string_scanner: ^1.1.1

dev_dependencies:
  lints: ^2.0.0
  checked_yaml: ^2.0.1
  test: ^1.16.0
  test_descriptor: ^2.0.0
  build_runner: ^2.0.0
  build_test: ^2.0.0
  json_serializable: ^6.2.0
  crypto: ^3.0.3
  glob: ^2.1.2

executables:
  drift_dev:
