site_name: Drift
site_description: Drift — A modern database library for Dart & Flutter
site_author: Simon Binder
site_url: https://drift.simonbinder.eu/
repo_url: https://github.com/simolus3/drift
# TODO: add edit_uri
# edit_uri:
theme:
  name: material
  language: en
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  # TODO: Add logo & favicon
  # logo: assets/logo.png
  # favicon: assets/favicon.ico
  features:
    - content.tooltips
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.expand
    - navigation.path
    - toc.follow
    - navigation.top
    - search.highlight
    - content.code.copy
    - content.code.annotate

extra:
  social:
    - icon: fontawesome/solid/paper-plane
      link: mailto:oss@simonbinder.eu
      name: Contact me via e-mail
    - icon: fontawesome/brands/github
      link: https://github.com/simolus3/drift
      name: Project on GitHub

  # TODO: Add Google Analytics
  # analytics:
  #     provider: google
  #     property: G-XXXXXXXXXX

plugins:
  - search
  - privacy
  - macros
  # - spellcheck

markdown_extensions:
  - admonition
  - pymdownx.details
  - attr_list
  - footnotes
  - toc:
      permalink: true
      toc_depth: 3
  - tables
  - pymdownx.highlight:
      auto_title: false
      anchor_linenums: true
      use_pygments: true

  - pymdownx.betterem

  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.critic
  - md_in_html

  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

copyright: >
  Copyright &copy; 2019 - 2024 Simon Binder –
  <a href="#__consent">Change cookie settings</a>
nav:
  - index.md
  - Reference:
      - Getting Started: setup.md
      - Dart API/tables.md
      - Dart API/columns.md

      - Dart API/dataclass.md
      - Dart API:
          - Dart API/manager.md
          - Dart API/tables.md
          - Dart API/select.md
          - Dart API/writes.md
          - Dart API/transactions.md
          - Dart API/expressions.md
          - Dart API/schema_inspection.md
          - Dart API/views.md
          - Dart API/daos.md
      - SQL API:
          - Getting Started: SQL API/index.md
          - SQL API/drift_files.md
          - SQL API/types.md
          - SQL API/extensions.md
          - SQL API/custom_queries.md
          # - SQL API/sql_ide.md
      - Migrations:
          - Getting Started: Migrations/index.md
          - Migrations/exports.md
          - Migrations/step_by_step.md
          - Migrations/tests.md
          - Migrations/api.md
      - type_converters.md
      - custom_row_classes.md
      - Generation options:
          - Getting Started: Generation options/index.md
          - Generation options/modular.md
          - Generation options/in_other_builders.md
      - Platforms:
          - Getting Started: Platforms/index.md
          - Platforms/vm.md
          - Platforms/web.md
          - Platforms/postgres.md
          - Platforms/encryption.md
          - Platforms/libsql.md
      - isolates.md
      - testing.md
      - CLI.md
      - faq.md
      - community_tools.md
      - Internals: Internals/index.md
      - migrating_to_drift.md
      - upgrading.md
  - Examples:
      - Examples/flutter.md
      - Examples/relationships.md
      - Examples/tracing.md
      - Examples/server_sync.md
      - Examples/existing_databases.md
      - Examples/more.md

  # - Getting Started:
  #     - getting-started/install.md
  #     - getting-started/schema.md
  # - Reference:
  #     - setup.md
  #     - type_converters.md
  #     - faq.md
  #     - testing.md
  #     - CLI.md
  #     - isolates.md
  #     - community_tools.md

docs_dir: "../docs"

extra_javascript:
  - path: compatibility.dart.js
    defer: true
extra_css:
  - "css/highlight.css"
watch:
  - "../lib"
