name: tooling
publish_to: none
description: Tools used during development or in CI runs

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  coverage: ^1.0.2
  path: ^1.8.0
  simons_pub_uploader:
    hosted:
      url: https://simonbinder.eu
      name: simons_pub_uploader
    version: ^1.0.2
