name: drift_mariadb
description: Mariadb support for drift.
version: 1.0.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  drift: ^2.0.0
  meta: ^1.9.1
  mysql_client: ^0.0.27

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
  drift_testcases:
    path: ../integration_tests/drift_testcases
