name: analyzer_load_moor_plugin
version: 1.0.0
description: This pubspec is a part of Drift and determines the version of the analyzer plugin to load

environment: 
  sdk: '>=2.9.0 <3.0.0'

dependencies:
  drift_dev: ^1.0.0
  web_socket_channel: ^1.0.15

# These overrides are only needed when working on the plugin with useDebuggingVariant = false (not recommended)

#dependency_overrides:
# drift_dev:
#  path: /path/to/drift/drift_dev
# sqlparser:
#  path: /path/to/drift/sqlparser
