name: drift_devtools_extension
description: A Flutter web app contribution drift tools to DevTools
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  devtools_extensions: ^0.2.1
  devtools_app_shared: ^0.2.1
  db_viewer: ^1.0.3
  rxdart: ^0.27.7
  flutter_riverpod: ^3.0.0-dev.0
  vm_service: ^14.0.0
  path: ^1.8.3
  drift: ^2.12.1
  logging: ^1.2.0
  url_launcher: ^6.1.14
  drift_dev: ^2.13.1
  sqlite3: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

dependency_overrides:
  web: ^0.5.0

flutter:
  uses-material-design: true
