name: flutter_web_worker_example
description: An absolute bare-bones flutter web app.

environment:
  sdk: "^3.3.0"
  flutter: ">=2.5.2"

dependencies:
  flutter:
    sdk: flutter
  path_provider: ^2.0.5
  drift:

dev_dependencies:
  build_runner: ^2.1.4
  build_web_compilers: ^4.0.3
  flutter_lints: ^4.0.0
  drift_dev:
