name: drift_flutter
description: Easily set up drift databases across platforms in Flutter apps.
version: 0.2.1-dev
repository: https://github.com/simolus3/drift
homepage: https://drift.simonbinder.eu/
issue_tracker: https://github.com/simolus3/drift/issues

topics:
  - drift
  - database

funding:
  - https://github.com/sponsors/simolus3

environment:
  sdk: ^3.3.0

dependencies:
  drift: ^2.21.0-dev
  flutter:
    sdk: flutter
  meta: ^1.3.0
  path: ^1.9.0
  path_provider: ^2.1.3
  sqlite3: ^2.0.0
  sqlite3_flutter_libs: ^0.5.24

dev_dependencies:
  build_runner: ^2.4.11
  drift_dev: ^2.21.0-dev
  lints: ^4.0.0
  test: ^1.24.0
  flutter_test:
    sdk: flutter
  test_descriptor: ^2.0.1
  async: ^2.11.0
