name: flutter_db
description: Testing drift's `NativeDatabase` on Flutter.
version: 1.0.0+1

publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=3.10.0"

dependencies:
  drift: ^2.0.0-0
  path: ^1.8.0
  sqlite3: ^1.7.2
  flutter:
    sdk: flutter
  drift_testcases:
    path: ../drift_testcases
  sqlite3_flutter_libs: ^0.5.7

dev_dependencies:
  test: ^1.18.0
  flutter_lints: ^2.0.1
  integration_test:
    sdk: flutter

dependency_overrides:
  drift:
    path: ../../../drift

flutter:
  assets:
    - test_asset.db
