name: encrypted_drift
description: Encryption support for drift, built with sqflite_sqlcipher
version: 1.0.0

environment:
  sdk: '>=2.12.0-0 <3.0.0'

dependencies:
  drift: ^2.0.0
  sqflite_sqlcipher: ^2.0.0

dev_dependencies:
  drift_testcases:
    path: ../integration_tests/drift_testcases
  flutter:
    sdk: flutter
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  path: ^1.8.1

dependency_overrides:
  drift:
    path: ../../drift
