name: drift_docs
publish_to: none
version: 1.0.0

environment:
  sdk: ^3.4.0

dependencies:
  drift:
  drift_postgres:
  path: ^1.8.2
  json_annotation: ^4.9.0
  code_snippets:
    hosted: https://simonbinder.eu
    version: ^0.0.13
  # used in snippets
  http: ^1.1.0
  sqlite3: ^2.0.0
  # Fake flutter packages for snippets
  path_provider:
  sqlite3_flutter_libs:
  sqlcipher_flutter_libs:
  drift_flutter:
  # Used in examples
  rxdart: ^0.27.3
  yaml: ^3.1.1
  drift_dev: any
  test: ^1.18.0
  postgres: ^3.0.0-0

dev_dependencies:
  build_runner: ^2.4.11
  build_verify: ^3.1.0
  lints: ^3.0.0
  build: ^2.1.0
  build_web_compilers: ^4.0.0
  json_serializable: ^6.1.6
  source_span: ^1.9.1
  sqlparser:

dependency_overrides:
  path_provider:
    path: stubs/path_provider
  sqlite3_flutter_libs:
    path: stubs/sqlite3_flutter_libs
  sqlcipher_flutter_libs:
    path: stubs/sqlcipher_flutter_libs
  drift_flutter:
    path: stubs/drift_flutter
  drift:
    path: ../drift
  drift_dev:
    path: ../drift_dev
  drift_postgres:
    path: ../extras/drift_postgres
  sqlparser:
    path: ../sqlparser
