name: drift_docs
description: Documentation website for the drift project.
publish_to: none

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  drift:
  drift_postgres:
  path: ^1.8.2
  json_annotation: ^4.8.1
  docsy:
    hosted: https://simonbinder.eu
    version: ^0.2.3
  code_snippets:
    hosted: https://simonbinder.eu
    version: ^0.0.13
  # used in snippets
  http: ^1.1.0
  sqlite3: ^2.0.0
  # Fake path_provider for snippets
  path_provider:
    path: assets/path_provider
  # Used in examples
  rxdart: ^0.27.3
  yaml: ^3.1.1
  drift_dev: any
  zap: ^0.2.0
  picocss:
    hosted: https://simonbinder.eu
    version: ^1.5.10
  test: ^1.18.0
  postgres: ^2.6.3

dev_dependencies:
  lints: ^2.0.0
  build: ^2.1.0
  build_runner: ^2.0.5
  build_runner_core: ^7.2.7
  build_web_compilers: ^4.0.0
  built_site:
    hosted: https://simonbinder.eu
    version: ^0.2.16
  json_serializable: ^6.1.6
  shelf: ^1.2.0
  shelf_static: ^1.1.0
  source_span: ^1.9.1
  sqlparser:
  zap_dev: ^0.2.3+1

dependency_overrides:
  # todo: Remove after https://github.com/dart-lang/mime/pull/43
  mime:
    git:
      url: https://github.com/simolus3/mime.git
      ref: woff2
