name: drift_docs
description: Documentation website for the drift project.
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  drift:
  drift_postgres:
  path: ^1.8.2
  json_annotation: ^4.9.0
  # used in snippets
  http: ^1.1.0
  sqlite3: ^2.0.0

  # Used in examples
  rxdart: ^0.27.3
  yaml: ^3.1.1
  drift_dev: any
  test: ^1.18.0
  postgres: ^3.0.0-0
  uuid: ^4.4.2
  sqlcipher_flutter_libs: ^0.6.4
  sqlite3_flutter_libs: ^0.5.24
  path_provider: ^2.1.4
  drift_flutter: ^0.2.0

dev_dependencies:
  build_runner: ^2.4.11
  build_verify: ^3.1.0
  lints: ^4.0.0
  build: ^2.1.0
  build_web_compilers: ^4.0.0
  json_serializable: ^6.1.6
  source_span: ^1.9.1
  sqlparser:
  characters: ^1.3.0
  args: ^2.5.0
  flutter_test:
    sdk: flutter

dependency_overrides:
  drift_flutter:
    path: ../drift_flutter
  drift:
    path: ../drift
  drift_dev:
    path: ../drift_dev
  drift_postgres:
    path: ../extras/drift_postgres
  sqlparser:
    path: ../sqlparser

flutter:
  uses-material-design: true
