name: drift_docs
description: Documentation website for the drift project.
publish_to: none

environment:
  sdk: '>=2.15.0 <3.0.0'

dependencies:
  drift:
  path: ^1.8.2
  json_annotation: ^4.6.0
  docsy:
    hosted: https://simonbinder.eu
    version: ^0.2.2
  code_snippets:
    hosted: https://simonbinder.eu
    version: ^0.0.8
  # used in snippets
  http: ^0.13.5
  sqlite3: ^1.7.2
  # Fake path_provider for snippets
  path_provider:
    path: assets/path_provider
  # Used in examples
  rxdart: ^0.27.3
  yaml: ^3.1.1
  drift_dev: any

dev_dependencies:
  lints: ^2.0.0
  build: ^2.1.0
  build_runner: ^2.0.5
  build_runner_core: ^7.2.3
  build_web_compilers: ^3.2.0
  built_site:
    hosted: https://simonbinder.eu
    version: ^0.2.10
  linkcheck: ^2.0.19
  json_serializable: ^6.1.6
  shelf: ^1.2.0
  shelf_static: ^1.1.0
  source_span: ^1.9.1
  sqlparser:


dependency_overrides:
  drift:
    path: ../drift
  drift_dev:
    path: ../drift_dev
  sqlparser:
    path: ../sqlparser

  # todo: Remove after https://github.com/dart-lang/mime/pull/43
  mime:
    git:
      url: https://github.com/simolus3/mime.git
      ref: woff2
