name: app
description: A cross-platform todo tracker built with drift.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  drift:
  drift_dev: ^2.8.1
  file_picker: ^5.2.5
  flutter_colorpicker: ^1.0.3
  flutter_riverpod: ^2.3.0
  go_router: ^6.2.0
  intl: ^0.18.0
  http: ^0.13.4 # used to load sqlite3 wasm files on the web
  sqlite3_flutter_libs: ^0.5.5
  sqlite3: ^2.0.0-dev.0
  path_provider: ^2.0.9
  path: ^1.8.0
  riverpod: ^2.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  build_runner: ^2.1.8
  # We use this to compile the shared web worker for the web database. This dependency
  # isn't required for most apps. You only need it if you want to target the web, use
  # web workers for drift AND want to compile those web workers through `build_runner`.
  # Either way, using this package with Flutter requires a delicate setup described in
  # `build.yaml`.
  build_web_compilers: ^3.2.2
  build: ^2.2.1

flutter:
  uses-material-design: true
