name: Documentation
on:
  push:
  pull_request:
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: dart-lang/setup-dart@v1
        with:
          sdk: beta
      
      # Temporarily using a custom dartdoc until https://github.com/dart-lang/dartdoc/issues/2755 is fixed
      - uses: actions/checkout@v2
        with:
          repository: simolus3/dartdoc
          path: ./dartdoc/
      - name: Setup dartdoc
        run: dart pub get
        working-directory: dartdoc

      - name: Get dependencies
        run: dart pub get
        working-directory: docs
      - name: Run build
        env:
          IS_RELEASE: ${{ github.event_name == 'push' && github.event.ref == 'refs/heads/master' }}
        run: dart run tool/ci_build.dart
        working-directory: docs

      - name: Deploy to netlify (Branch)
        if: ${{ github.event_name == 'push' }}
        uses: nwtgck/actions-netlify@v1.2
        with:
          production-branch: master
          publish-dir: docs/deploy
          enable-pull-request-comment: true
          enable-commit-comment: false
          netlify-config-path: "./netlify.toml"
          github-token: ${{ secrets.GITHUB_TOKEN }}
          alias: ${{ github.head_ref }}
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
      - name: Deploy to netlify (Pull Request)
        if: ${{ github.event_name == 'pull_request' }}
        uses: nwtgck/actions-netlify@v1.2
        with:
          production-branch: master
          publish-dir: docs/deploy
          enable-pull-request-comment: true
          enable-commit-comment: false
          netlify-config-path: "./netlify.toml"
          github-token: ${{ secrets.GITHUB_TOKEN }}
          alias: deploy-preview-${{ github.event.number }}
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}

# The documentation on pub is currently broken
#  linkcheck:
#    name: Check links in markdown
#    runs-on: ubuntu-20.04
#    steps:
#      - uses: actions/checkout@master
#      - uses: gaurav-nelson/github-action-markdown-link-check@v1
